#!/bin/bash

THREADS=${1:-10}
echo "Using $THREADS threads."

rm -rf frames/*

echo "Getting list of streamers..."
STREAMERS=$(php ../tdf/run.php tdf:find "Dota 2")
echo "$STREAMERS" | wc -l

parallel -j$THREADS -k 'python3 d2f.py {}' ::: $STREAMERS
